/* Generated By:JavaCC: Do not edit this line. PsqlConstants.java */
package net.prolog.sql;

public interface PsqlConstants {

  int EOF = 0;
  int K_SELECT = 5;
  int K_FROM = 6;
  int S_IDENTIFIER = 7;
  int LETTER = 8;
  int SPECIAL_CHARS = 9;
  int S_BIND = 10;
  int S_CHAR_LITERAL = 11;
  int S_QUOTED_IDENTIFIER = 12;
  int INTEGER = 13;
  int DIGIT = 14;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"SELECT\"",
    "\"FROM\"",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_BIND>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "<INTEGER>",
    "<DIGIT>",
    "\";\"",
    "\",\"",
    "\"*\"",
    "\".\"",
    "\"(\"",
    "\")\"",
  };

}
